module.exports = {
  filterButtons: require('./pages/catalogPage/filterButtons'),
  prices: require('./pages/catalogPage/prices'),
  filterShowButtons: require('./pages/catalogPage/filterShowBtns'),
  filterClearButtons: require('./pages/catalogPage/filterClearBtns'),
  filterBlocks: require('./pages/catalogPage/filterBlocks'),
  filteredProducts: require('../helpers/pages/catalogPage/filteredProducts').filteredProducts,
  filterElems: require('./pages/catalogPage/filterElems').filterElems,

  emailRValidation: require('./validation/emailRValidation').emailRValidation,
  passwordValidation: require('./validation/passwordValidation').passwordValidation,
  deliveryAddressValidation: require('./validation/deliveryAddressValidation').deliveryAddressValidation,
  stringWithoutSpacesValidation: require('./validation/stringWithoutSpacesValidation').stringWithoutSpacesValidation,
  onlyNumbersValidation: require('./validation/onlyNumbersValidation').onlyNumbersValidation,
  cyrillicValidation: require('./validation/cyrillicValidation').cyrillicValidation,
  cardNumberValidation: require('./validation/cardNumberValidation').cardNumberValidation,
  telValidation: require('./validation/telValidation').telValidation,
  loginValidation: require('./validation/loginValidation').loginValidation,
  numberValidation: require('./validation/numberValidation').numberValidation,

  myProfileElemNames: require('./components/profile/myProfileElemNames').myProfileElemNames,
  authElemNames: require('./components/authorization/authElemNames').authElemNames,
  regElemNames: require('./components/registration/regElemNames').regElemNames,
  headerElemsNames: require('./components/header/headerElemsNames').headerElemsNames,
  personalSettingsElemNames: require('./components/personalSettings/personalSettingsElemNames').personalSettingsElemNames,
  favoriteElemNames: require('./components/favorite/favoriteElemNames').favoriteElemNames,
  searchElemNames: require('./components/search/searchElemNames').searchElemNames,
  basketElemNames: require('./components/basket/basketElemNames').basketElemNames,
  searchFilters: require('./components/search/searchFilters').searchFilters,
  securitySettingsElemNames: require('./components/securitySettings/securitySettingsElemNames').securitySettingsElemNames,
  orderFormElemNames: require('./components/orderForm/orderFormElemNames').orderFormElemNames,
  productCardElemNames: require('./components/productCard/productCardElemNames').productCardElemNames,
}
