module.exports = {
  productCard: require('./catalog/productCard').ProductCard,
  registrationFrom: require('./singInUp/registrationForm'),
  authorizationForm: require('./singInUp/authorizationForm'),
  myProfile: require('./profile/myProfile'),
  favoriteComp: require('./profile/favoriteComp'),
  basketComp: require('./profile/basketComp'),
  orderHistoryComp: require('./profile/orderHistoryComp'),
  orderForm: require('./profile/orderForm'),
  personalSettings: require('./profile/personalSettings'),
  securitySettings: require('./profile/securitySettings'),
  error: require('./popup/error'),
  search: require('./pagesComponents/searchComp'),
  message: require('./popup/message'),
  header: require('./pagesComponents/header').header,
}
