export const regElemNames = [
  'registration-form',
  'login',
  'password',
  'avatar',
  'message',
  'picture',
  'submit',
  'verify-password',
  'password-message',
  'close-btn',
  'reg-link',
  'set-avatar',
  'set-phone',
  'shadow',
]
